# Use this one if deploying to production.
application: hdj-signup
# Use this one if deploying to dev.
#application: signup-dev
version: 4
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.app
- url: /my_billing
  script: billing.app
  login: required
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.handler.app
  login: admin
- url: /_km/.*
  script: keymaster_handler.app
  login: admin
- url: /api/v1/.*
  script: user_api.app
- url: /cron/.*
  script: cron.app
- url: /tasks/.*
  script: tasks.app
- url: .*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
