application: hd-signup-hrd
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.handler.app
  login: admin
- url: /_km/.*
  script: keymaster.app
  login: admin
- url: .*
  script: main.app

builtins:
- remote_api: on
